steps:
  # 0. Docker Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'us.gcr.io/kin-project-352614/django-cloudrun/cicd:myimagev1'
      - .
      - '-f'
      - Dockerfile
    id: Build

  # 1. Docker push to Google Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us.gcr.io/kin-project-352614/django-cloudrun/cicd:myimagev1'
    id: Push

  # 2. Make migrations
  - name: gcr.io/google-appengine/exec-wrapper
    args:
      - '-i'
      - 'us.gcr.io/kin-project-352614/django-cloudrun/cicd:myimagev1'
      - '-s'
      - 'kin-project-352614:europe-west1:django-dev-db'
      - '-e'
      - 'SETTINGS_NAME=django_app_settings'
      - '--'
      - 'python'
      - 'manage.py'
      - 'makemigrations'
    id: Make migrations

  # 3. Migrate
  - name: gcr.io/google-appengine/exec-wrapper
    args:
      - '-i'
      - 'us.gcr.io/kin-project-352614/django-cloudrun/cicd:myimagev1'
      - '-s'
      - 'kin-project-352614:europe-west1:django-dev-db'
      - '-e'
      - 'SETTINGS_NAME=django_app_settings'
      - '--'
      - 'python'
      - 'manage.py'
      - 'migrate'
    id: Migrate

    # 4. Collect static
  - name: gcr.io/google-appengine/exec-wrapper
    args:
      - '-i'
      - 'us.gcr.io/kin-project-352614/django-cloudrun/cicd:myimagev1'
      - '-s'
      - 'kin-project-352614:europe-west1:django-dev-db'
      - '-e'
      - 'SETTINGS_NAME=django_app_settings'
      - '--'
      - 'python'
      - 'manage.py'
      - 'collectstatic'
      - '--no-input'
    id: Collect static

  # 5. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - cicd
      - '--platform=managed'
      - '--image=us.gcr.io/kin-project-352614/django-cloudrun/cicd:myimagev1'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=myimagev1,gcb-build-id=hailat_build_id,gcb-trigger-id=hailat_trigger,gcp-trigger-id-hailat_trigger
      - '--region=europe-west1'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

# Store images in Google Artifact Registry
images:
  - 'us.gcr.io/kin-project-352614/django-cloudrun/cicd:myimagev1'

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed